baseURL = "https://chinderzytig-v1.netlify.app/"
languageCode = "de"
title = "Chinderzytig - Die Zeitung f√ºr Kinder und Jungendliche"
[params]
    DateForm = "6.1.2006"
		cloudinary_url = "https://res.cloudinary.com/chinderzytig/image/upload"
